# Generated by Django 2.1.14 on 2019-12-24 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='业务名称')),
                ('shortname', models.CharField(max_length=32, verbose_name='业务简称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('life_cycle', models.IntegerField(choices=[(1, '测试'), (2, '上线'), (3, '下线')])),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='组件名称')),
            ],
        ),
        migrations.CreateModel(
            name='EsCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='集群名')),
                ('version', models.CharField(blank=True, max_length=32, verbose_name='版本')),
                ('health', models.IntegerField(choices=[(1, 'red'), (2, 'yellow'), (3, 'green')], default=3)),
                ('master', models.GenericIPAddressField()),
                ('is_enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EsHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrafanaFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='仪表盘名称')),
                ('url', models.CharField(max_length=255, verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='GrafanaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('folder_title', models.CharField(max_length=32, verbose_name='文件夹名称')),
                ('folder_id', models.IntegerField(verbose_name='文件夹id')),
                ('folder_uid', models.CharField(max_length=32, verbose_name='文件夹uid')),
                ('user', models.CharField(max_length=32, verbose_name='日志系统用户')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=64, null=True)),
                ('os', models.IntegerField(choices=[(1, 'Linux'), (2, 'Windows'), (3, 'Other')], default=3)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_to_one', models.BooleanField()),
                ('index_suffix', models.CharField(max_length=64, verbose_name='索引后缀')),
                ('index_period', models.IntegerField(choices=[(1, 'daily'), (2, 'monthly'), (3, 'yearly')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='LogAlarmCompress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.IntegerField(verbose_name='时间窗口')),
                ('interval_time', models.IntegerField(verbose_name='时间间隔')),
                ('total_number', models.IntegerField(verbose_name='告警总次数')),
            ],
        ),
        migrations.CreateModel(
            name='LogAlarmExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64, verbose_name='字段名')),
                ('operator', models.CharField(max_length=3, verbose_name='运算符')),
                ('value', models.CharField(max_length=64, verbose_name='关键字或阀值')),
            ],
        ),
        migrations.CreateModel(
            name='LogAlarmRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='告警规则名')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
                ('businessID', models.IntegerField(verbose_name='所属业务ID')),
                ('alarm_depth', models.IntegerField(choices=[(1, '业务级别'), (2, '组件级别')], verbose_name='告警深度')),
                ('componentID', models.IntegerField(blank=True, verbose_name='组件ID')),
                ('level', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '极高')], verbose_name='告警级别')),
                ('title', models.CharField(max_length=255, verbose_name='告警标题')),
                ('message', models.TextField(verbose_name='告警内容')),
                ('alarm_date', models.IntegerField(choices=[(1, '工作日'), (2, '全年')], verbose_name='告警周期')),
                ('expression', models.CharField(max_length=64, verbose_name='告警表达式')),
                ('enabled', models.BooleanField(verbose_name='生效')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('alarm_compress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.LogAlarmCompress', verbose_name='告警压缩')),
            ],
        ),
        migrations.CreateModel(
            name='LogAlarmTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '全天'), (2, '工作时段')], verbose_name='时段类型')),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='字段名称')),
                ('type', models.IntegerField(choices=[(1, 'Integer'), (2, 'String')])),
                ('description', models.CharField(max_length=128, verbose_name='说明')),
                ('enabled', models.BooleanField(verbose_name='已启用')),
                ('default', models.BooleanField(verbose_name='默认字段')),
                ('business', models.ManyToManyField(to='adminApp.Business')),
                ('component', models.ManyToManyField(blank=True, to='adminApp.Component')),
            ],
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='alarm_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.LogAlarmTime', verbose_name='告警时段'),
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='notifier',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='通知用户'),
        ),
        migrations.AddField(
            model_name='escluster',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='adminApp.EsHost'),
        ),
        migrations.AddField(
            model_name='component',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='adminApp.Host'),
        ),
        migrations.AddField(
            model_name='business',
            name='components',
            field=models.ManyToManyField(blank=True, to='adminApp.Component'),
        ),
        migrations.AddField(
            model_name='business',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
