# Generated by Django 2.1.14 on 2019-12-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_auto_20191225_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='logalarmrule',
            name='notify_way',
            field=models.IntegerField(choices=[(1, '邮箱'), (2, '短信'), (3, 'API')], default=1, verbose_name='通知方式'),
            preserve_default=False,
        ),
    ]
