# Generated by Django 2.1.14 on 2019-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_logalarmrule_notify_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logalarmrule',
            name='alarm_compress',
        ),
        migrations.RemoveField(
            model_name='logalarmrule',
            name='alarm_time',
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='end_time',
            field=models.TimeField(blank=True, default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='interval_time',
            field=models.IntegerField(default=3, verbose_name='时间间隔'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='start_time',
            field=models.TimeField(blank=True, default='13:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='time_type',
            field=models.IntegerField(choices=[(1, '全天'), (2, '工作时段')], default=2, verbose_name='时段类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='total_number',
            field=models.IntegerField(default=10, verbose_name='告警总次数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logalarmrule',
            name='total_time',
            field=models.IntegerField(default=10, verbose_name='时间窗口'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LogAlarmCompress',
        ),
        migrations.DeleteModel(
            name='LogAlarmTime',
        ),
    ]
