# Generated by Django 2.1.14 on 2019-12-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_auto_20191225_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='logalarmrule',
            name='compress_enabled',
            field=models.BooleanField(default=1, verbose_name='压缩启用'),
            preserve_default=False,
        ),
    ]
