# Generated by Django 2.1.14 on 2019-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_logalarmrule_compress_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='APINotifyWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='通知方式')),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='APINotifyWayColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32, verbose_name='字段名')),
                ('type', models.CharField(max_length=32, verbose_name='字段类型')),
                ('description', models.CharField(max_length=64, verbose_name='说明')),
            ],
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='notify_way',
            field=models.CharField(max_length=64, verbose_name='通知方式'),
        ),
        migrations.AddField(
            model_name='apinotifyway',
            name='field',
            field=models.ManyToManyField(blank=True, to='adminApp.APINotifyWayColumn'),
        ),
    ]
