# Generated by Django 2.1.14 on 2019-12-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_auto_20191226_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='logalarmexpression',
            name='rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.LogAlarmRule'),
            preserve_default=False,
        ),
    ]
