# Generated by Django 2.1.14 on 2019-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_auto_20191227_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='logalarmexpression',
            name='expression_id',
            field=models.CharField(default=1, max_length=2, verbose_name='表达式标识'),
            preserve_default=False,
        ),
    ]
