# Generated by Django 2.1.14 on 2019-12-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0014_auto_20191227_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logalarmrule',
            name='componentID',
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='component',
            field=models.IntegerField(blank=True, null=True, verbose_name='组件ID'),
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='interval_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='时间间隔'),
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='total_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='告警总次数'),
        ),
        migrations.AlterField(
            model_name='logalarmrule',
            name='total_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='时间窗口'),
        ),
    ]
