# Generated by Django 2.1.14 on 2019-12-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0015_auto_20191227_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
    ]
