# Generated by Django 2.1.14 on 2019-12-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0016_alerthost'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthost',
            name='enabled',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
